### ISSUE TITLE
Great idea! Release?

### ISSUE THREAD

**Issue by fluffynuts** [muan/paint-github#1]
![paint](https://user-images.githubusercontent.com/4669340/68736569-a27f6c00-05e9-11ea-8c83-3b3370e31ff9.png)

Some thoughts:
- Please release to addons.mozilla.org and the chrome store! I've gotten this to work in "developer mode" on Firefox, but I'm not even sure yet how to package it into an .xpi for my own use. I'm sure there are other people who would like this!
- Please have a look at styling for the two buttons: currently they seem to be styled as white, instead of taking on GitHub styles. This doesn't play well with things like Dark Reader or Stylus. Attached screenshot with Dark Reader.

![image](https://user-images.githubusercontent.com/4669340/68736659-f25e3300-05e9-11ea-9a94-8db5f3a5a60f.png)

**Comment by muan** [comment]
Hey! Thanks for the issue. I made the second change.

I don't want to release yet because it's very early stage and many things are in flux/don't work great. I feel like cutting a release would make the project open to bug reports for things I just haven't had the time to work on yet.

**Comment by fluffynuts** [comment]
:+1: 

It's your baby, but, if you have the time, read a little thing I wrote: https://dev.to/fluffynuts/perfect-is-the-enemy-of-good-4hek

- you're already featured on changelog emails
- it already does the minimum quite well

**Comment by tg-z** [comment]
![paint](https://user-images.githubusercontent.com/47585455/69210171-bc9bdb80-0b0e-11ea-8375-680795d43c8b.png)

**Comment by muan** [comment]
> * you're already featured on changelog emails

Oh I didn't know this. Do you have a link?

**Comment by fluffynuts** [comment]
The Changelog sends an email with trending repos out every day -- so if I've seen it, I bet quite a few other people have seen it. I think it's automated from starring. The point is that I expect you would have had quite a few people visiting your repo, and many would probably be interested in using your project (: IOW, this project is not "unknown" any more (:

**Comment by fluffynuts** [comment]
https://github.com/thechangelog/nightly

**Comment by muan** [comment]
Thanks. Here’s the Firefox Addon listing: https://addons.mozilla.org/en-US/firefox/addon/paint-github/

Chrome rejected it saying it seems spammy. 🤷🏻‍♀️

**Comment by fluffynuts** [comment]
gah! try again perhaps? is there anything a fan can do to help?

**Comment by muan** [comment]
https://github.com/muan/paint-github/commit/e9ccb223129d333dfd26fb2e96f993cf02584b5a
